spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.102/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: F://日志
#  file: F://日志/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wxdcf91e9f784bfad0
  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  mchId: 1483469312
  mchKey: 06C56A89949D617DEF52F371C357B6DB
  keyPath: F:\\h5.p12
  nofifyUrl: http://sqmax.natapp1.cc/sell/pay/notify